url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "academic" # the name of your site, e.g. ACME Corp.
description: "a Jekyll theme for academia"

remote_theme: "mmistakes/minimal-mistakes@4.26.1"

plugins:
  - jekyll-include-cache
