menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/mackeynations'}


contacts:
- {name: 'Wyatt Mackey, title: 'Postdoc', department: 'National Institute for Modeling Biological Systems', institution: 'University of Tennessee', phone: '(801) 503-5271', email: 'wmackey2@utk.edu', image: 'assets/img/contact.jpg'}
